Team 3
CMPSC-203-Allegheny-College-Fall-2022/code-of-conduct pull request #10
Opened 2022-09-06 19:16 UTC by brum0505

## Description

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [ x] Documentation

## Contributors

- @brum0505 
- @Barker0103 
- @tmiller-10 
- @Darius90332 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-09-06 19:22 UTC, jnormile reviewed
Commented in the document with a few small grammar fixes. Additionally, there's some inconsistency with bullet points ending both with and without periods. I posted in Discord asking what the preferred format is if we all want to come to a consensus regarding that.

2022-09-06 19:22 UTC, jnormile commented on conduct.md
> +- Students should try to understand the other persons point of view.
*person's

2022-09-06 19:22 UTC, jnormile commented on conduct.md
> +- Acceptable work would also consist following the Honor Code from Allegheny College with work in the class
*consist of

2022-09-06 19:22 UTC, jnormile commented on conduct.md
> +- Unacceptable work would consist of being turning in work late after a certain deadline.
omit "being"

2022-09-06 19:33 UTC, jjumadinova requested changes
Please address comments provided for lines 132 and 138.

2022-09-06 19:33 UTC, jjumadinova commented on conduct.md
> +- Acceptable work would be turning work in to the class on time.
Can this be rephrased to make it more clear? Not clear what is meant by "turning work in to the class".

2022-09-06 19:33 UTC, jjumadinova commented on conduct.md
> +- Unacceptable work would consist of being turning in work late after a certain deadline.
Agree with @jnormile

2022-09-06 19:51 UTC, solisa986 requested changes
Good work on your first pull request! I have outlined some changes that I will need to be addressed prior to my re-review. Once you have made all of the change, please mark the conversations as resolved and re-request my review :)

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +Students experiencing conflicts should come together to fix the problem. No argument
You might want to split the second sentence into 2 sentences (from where the comma is).

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +conflicts in the class. When dealing with conflicts if resolutions cannot be resolved
Please add a comma after 'with conflicts' and after 'be resolved'.

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +then they should take conflicts to professor to resolve said issues. Lastly students
Please change 'professor' to 'the Professor'. Additionally, please add a comma after 'Lastly'.

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +- Students should not get angry at the other person.
Please change 'the other person' to 'other individuals'.

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +conducts in the class, and that will lead
please add either 'you' or 'the students' after 'will lead' to show who this paragraph is referring to.

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +Below, we will be outlining what is acceptable and unacceptable conduct. If followed,
You might want to confirm with the rest of the class whether you want to use personal or impersonal languages. Ergo, whether you want to use first-person language ('I, we, me, you') or whether you will use third-person language, such as ('they, their, the <group>, etc.').

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +- Unacceptable work would consist of being turning in work late after a certain
You might want to change 'after a certain' to 'after the posted', since this will leave less variability between deadlines

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +- Unacceptable work would also consist of not following other class rules and taking
Please remove 'also' from this bullet point and add a period to the end.

2022-09-06 19:51 UTC, solisa986 commented on conduct.md
> +- Unacceptable work would also contain not doing the work in the class and not
Please remove 'also' from this bullet point.

2022-09-06 20:20 UTC, hinckleyc approved these changes
Everything looks good. Good job.

2022-09-06 20:38 UTC, EstebanMendez01 approved these changes
Looks good!

2022-09-06 23:18 UTC, burgess01 approved these changes
Looks good!

2022-09-08 14:29 UTC, Makell-Logan approved these changes

2022-09-08 15:00 UTC, solisa986 approved these changes
looks good! Great work everyone :)

2022-09-08 20:35 UTC, jjumadinova approved these changes
I think it looks fine now.

2022-09-08 20:38 UTC, merged