Team2 Contributions
CMPSC-203-Allegheny-College-Fall-2022/code-of-conduct pull request #12
Opened 2022-09-06 20:02 UTC by jnormile

## Description

Team 2's cumulative proposed changes

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [x] Documentation

## Contributors

- @jnormile 
- @AidanNeeson 
- @ningerson2002 
- @gormley01 
- @brendengray 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

2022-09-06 20:03 UTC, favourojo approved these changes
All looks good to me!

2022-09-06 20:04 UTC, solisa986 approved these changes
Looks good! Thank you @jnormile @AidanNeeson @ningerson2002 @brendengray @gormley01 for your hard work on this!

2022-09-06 20:06 UTC, ColeKaupelis approved these changes

2022-09-06 20:09 UTC, burgess01 requested changes
This looks great! Please fix these errors and I think it should be ready to be merged.

2022-09-06 20:09 UTC, burgess01 commented on conduct.md
> +- Be proactive about communicating. This can include utilizing whatever platforms necessary to let other know ahead of time of any kinds of changes, concerns, or ideas.
change 'other' to 'others'

2022-09-06 20:09 UTC, burgess01 commented on conduct.md
> +Students are discouraged to:
Maybe 'discouraged from' would flow better? That is personal preference though, if you want to keep it as is thats fine!

2022-09-06 20:09 UTC, burgess01 commented on conduct.md
> +- Create decision that mutually benefit each other (Schedules, Coding). This is to help understand each other's responsibilities and respect on what is possible for both individual interest and the t
Change 'decision' to 'decisions'. Also, please reword the second sentence.

2022-09-06 20:09 UTC, burgess01 commented on conduct.md
> +- Never informing on others on unattended appointments. This will only create more problems as other team members has to do more work unexpectedly, therefore the work will not be as good as intended
Please reword this, especially the first sentence.

2022-09-06 20:09 UTC, burgess01 commented on conduct.md
> +- Always be transparent on what are we doing wrong with. The reason being is because to create a mutual relationship environment between the team to understand the good and the bad of the activity to
Please reword this.

2022-09-06 20:09 UTC, burgess01 commented on conduct.md
> +- Never create unnecessary mistakes (Forget to git pull, never creating pull requests). This is very important to not create more problems and not to halt on the team's progress on the work.
Maybe change 'This is very important to not create more problems' to something like 'It is very important not to create more problems'.

2022-09-06 20:15 UTC, Darius90332 approved these changes

2022-09-06 20:15 UTC, Darius90332 commented on conduct.md
> +Communication is the cornerstone of collaboration, and all communications for team-based activities in the Software Engineering course must adhere to the below guidelines for professionalism. To be c
Maybe emphasize how important communication will be considering teams won't always be the same

2022-09-06 20:18 UTC, merged

2022-09-07 15:05 UTC, benfarrah01 commented
Everything looks good to me! Nice job, these are good points for the code of conduct.